### 0. Health check
GET {{host}}/api/v1/health

### 1. Sign Up or Log In
POST {{host}}/api/v1/login
Content-Type: application/json

{
  "name": "강지혁",
  "password": "1234"
}

### 2. Get all paths
GET {{host}}/api/v1/path/search?originName=송도해경&destinationName=강남역&departureTime=2023-06-27T13:00:00

### 2-1. Get paths by id
GET {{host}}/api/v1/path/1

### 3. Reserve Bus
POST {{host}}/api/v1/reservation
Content-Type: application/json
Authorization: Bearer --

{
  "busId": 1,
  "getOnBusStop": "서울대입구역",
  "reservationRequestDatetime": "2023-06-26T16:49:00"
}