version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: mysql-server
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: tport
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)
    networks:
      - t-port
    healthcheck:
      test: [ 'CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD' ]
      interval: 10s
      timeout: 2s
      retries: 100

  t-port:
    container_name: t-port
    environment:
      DATABASE_URL: r2dbc:mysql://127.0.0.1:3306/tport
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - t-port
    depends_on:
      db:
        condition: service_healthy

networks:
  t-port: